### ISSUE TITLE
Incompatibility with latest Casadi v3.6.*

### ISSUE THREAD

**Issue by renatoloureiro** [iFR-ACSO/casos#16]
The current interface with CasADi [2cdeb4f](https://github.com/iFR-ACSO/casos/commit/2cdeb4fda8700fa36f8ff9d7ab7c24bc8621fe05) results in an error with the function handle if the CasADi version is v3.6.*

1. add to README.md the working version of CasADi
2. Update the interface to handle the latest version of CasADi.

**Comment by tcunis** [comment]
Perhaps you could briefly elaborate on the error? At least, please add the error and the line that caused the error.

**Comment by tcunis** [comment]
There are few use cases of `casadi.Function` which result in an error in Casadi v3.6.* but haven't in v3.5.5. Some of those can be avoided by setting appropriate options.
