### ISSUE TITLE
subs(p,x,a) is not working properly in some cases

### ISSUE THREAD

**Issue by JOlucak** [iFR-ACSO/casos#22]
- [ ] subs(p,x,0) is not working. It always returns 0
- [x] subs(p,x,a) where x \in \mathbb R^n and  a \in \mathbb R^{n x r}  is not working, i.e., if several/many values need to be inserted (for example for contour plot)

**Comment by tcunis** [comment]
> subs(p,x,a) where x \in \mathbb R^n and a \in \mathbb R^{n x r} is not working

Won't fix this. The intended (and only) way to evaluate a polynomial *like a function* is to [convert it to a `casadi.Function` object](https://github.com/iFR-ACSO/casos/blob/9b413d4a9ac0cf6c554156b62a33ff1dfd58cde4/%2Bcasos/%40PS/PS.m#L285) and evaluate the function instead (with casadi dealing with repeated evaluations:

```
f = to_function(p);
y = f(a);
```
