### ISSUE TITLE
PS.blkdiag takes very long

### ISSUE THREAD

**Issue by JOlucak** [iFR-ACSO/casos#24]
<img width="1894" alt="Unbenannt" src="https://github.com/iFR-ACSO/casos/assets/61011693/134490c5-91bb-4600-bfcb-fe7f66bef256">
![grafik](https://github.com/iFR-ACSO/casos/assets/61011693/674949a1-9b7b-4f55-a7ac-8d79d3a6f5f8)
<img width="1416" alt="Unbenannt2" src="https://github.com/iFR-ACSO/casos/assets/61011693/113f2d6a-ec3b-41e1-aa1b-6e3b3101a5bf">

**Comment by tcunis** [comment]
We need to avoid using `nonzeros` as it returns a cell array of scalar `SX` objects rather than one vector `SX` instance.
