### ISSUE TITLE
Storing PS objects in .mat files not possible

### ISSUE THREAD

**Issue by JOlucak** [iFR-ACSO/casos#25]
If you calculated/defined a polynomial object and try to save it in Matlab you first obtain a warning:
"
>Warning: Serializing SWIG objects not supported. 
> In SwigRef.loadobj (line 34)
In roaSatelliteStateConCons (line 18) 
"

If you load the .mat file to workspace and try to e.g. print the stored polynomial to the command window an error :

"
>Check for incorrect argument data type or missing argument in call to function 'is_symbolic'.

>Error in casos.PS/str (line 26)
>        if is_symbolic(cf)

>Error in casos.PS/disp (line 9)
>s = str(obj);
"

Error does not only occur in case of printing i.e. also for other operations.

Maybe we can implement a "saving" function such that the polynomial (PS object) is stored correctly.

**Comment by tcunis** [comment]
It appears the problem is on CasADi's side, we would need to find a way to store `casadi.SX` objects.

**Comment by JOlucak** [comment]
As a first work around/solution we can think about storing a polynomial with non-casadi elements in a struct. A second function could be used to do the conversion from struct to polynomial. 

See screenshot, 
<img width="528" alt="Unbenannt" src="https://github.com/iFR-ACSO/casos/assets/61011693/6194a82a-4075-420f-9a7f-c2402e89a745">

**Comment by tcunis** [comment]
Nonsymbolic polynomials can now be loaded & saved to mat-files. It's a workaround right now and there is still a warning, but it appears the warning can be ignored.
