### ISSUE TITLE
High computational effort due to Jacobian calculation and simplification operations in SdpSolInternal

### ISSUE THREAD

**Issue by JOlucak** [iFR-ACSO/casos#38]
It seems that the jacobian calculation and simplification in SdpSolInternal are responsible for the high computational effort in the solver building process.  See first figure. Currently, only simple cost functions (level sets) are considered. I think if more sphisticated cost functions are used in the future this becomes even more a bottleneck since the hessian calculation becomes more difficult. 
<img width="391" alt="sdpsolinternal" src="https://github.com/iFR-ACSO/casos/assets/61011693/afd57cc4-ed9d-46a6-b840-591b6c127dc2">

For small sized problems (such as VDP) this is not a bigger deal. However, for medium size (6 states) and higher order polynmials (e.g. 6) we run into high numerical effort. See figure 2. 

![image (1)](https://github.com/iFR-ACSO/casos/assets/61011693/714d2d45-592a-45e7-8917-9e4956eccdf8)

I am aware that polynomials of degree 6 are already quiet large but if we want to solve larger systems in the future or to have less conservative results this should be improved.
Is it possible to improve this computation in casadi? What else is possible?

**Comment by JOlucak** [comment]
Current status
- simplification is removed; for the case with only one constraint not fully tested with other example
- Simple test using casadi SX or mx to compute a random jacobian with different number of decision variables revealed that MX scales better
- First version that is capable to provide analytical parts of the Jacobian is in the repository; it does not work for several constraints and is hence not ready for useage yet

**Comment by JOlucak** [comment]
A first version to analytical calculate dg/dQg where g are the constraint functions and Qq the matrix decision variables. The implementation was is tested with the GTM example in different ways:
1. Calculate jacobian fully with casadi --> solve quasiconvex SOS problem to get reference values
2. Calculate jacobian partially with casadi and partially analytically --> solve quasi-convex problem and compare final results

We receive the same results. The computation of the analytical part can be neglect (compared to other more demanding parts) but can be implemented more efficiently.

The third test was by varying the polynomial and SOS decision variables (max degree). The "new" approach works but is only slightly  more efficient for a few reasons:
1. The "heavy" computations, regarding the jacobian, come from dg/dx (x are the SOS decision variables) and and dg/dxl, the linear decision variables. 
2. Altoough not that much (as for now) we must concatenate (potentially) large matrices to get the overall jacobian.

I will continue working on that.

**Comment by JOlucak** [comment]
Additional remarks:
- it seem that dg/dx  is the driver here i.e. takes the longest, dg/dxl is about 3-4x faster but it still takes rather long.

**Comment by JOlucak** [comment]
I found a weird behaviour I can't explain. 

If we set up a problem, rather large, and compute the jacobian for different parts (instead of for all dec. var at once), the computation times differ a lot.

dg/dQgram_g ~ 6s
dg/dQlin_x ~400s 

Now the weird part is the size
g              = 72295 x 1 SX
Qgram_g =  1123544x1 SX
Qlin_x      =  1x4350 SX

dgdQgram_g = 72295 x  1123544
dgdQlin_x      = 72295 x  4350

I don't understand why the latter one takes so much longer. g is the same.

the expressions in Qgram_g and Qlin_x are just SX variables that are the coefficients/decision variables. So not really a difference in the expressions.

Espacially, the last screenshot shows an ecpression of g and the Qgram_g and Qlin_x. I don't see a reason why it is more difficult to compute for Qlin_X

See screenshots
![grafik](https://github.com/iFR-ACSO/casos/assets/61011693/47d06a4c-0495-4060-acb7-c882bef33e7e)
![grafik](https://github.com/iFR-ACSO/casos/assets/61011693/566a3fd7-939a-4211-ba83-0b2e0015ebd7)
![grafik](https://github.com/iFR-ACSO/casos/assets/61011693/506be7da-3cb3-41e8-9b70-002ba2da08e4)
![grafik](https://github.com/iFR-ACSO/casos/assets/61011693/6065ea78-ea4c-42e7-9b8d-bb7205c01b7e)

**Comment by JOlucak** [comment]
Remark to previous comment.
- Maybe it has somethin to do that Qlin_x consists of differnt entries rather than only one i.e. in Qgram_g there are only "Q" terms.

**Comment by tcunis** [comment]
The variables of `Qgram_g` enter into the constraint in a very structured manner, i.e., the partial derivative is either zero or an integer. On the other hand, `Qlin_x` enters as arbitrary expression.
