### ISSUE TITLE
Certain problems from the literature are infeasible

### ISSUE THREAD

**Issue by JOlucak** [iFR-ACSO/casos#39]
It seems that some problem from the literature are feasible e.g. in sosopt but not in casos. Both problems are set up  with same multiplier etc. .  It is unclear to me why casos returns infeasible. I will investigate in more closely for some examples below

- [x] GTM reachability
- [ ] Penduot reachability

**Comment by tcunis** [comment]
Is this still relevant?

**Comment by tcunis** [comment]
Perhaps these examples are feasible with simplification?

**Comment by JOlucak** [comment]
GTM reachabililty can be computed. The main "error" source was the biscetion i.e. tolerances. For pendubot, I've to check.

**Comment by JOlucak** [comment]
Should be fixed by now. The main problem were the bounds used in bisection i.e. it was not related to the toolbox itself. Pendubot should be part of the example package
