### ISSUE TITLE
Option to turn on/off error message from underlying solver

### ISSUE THREAD

**Issue by JOlucak** [iFR-ACSO/casos#62]
In some solution algorithsm (bisection or sequential SOS) it is possible that an iterate/current trial is infeasible. In that case it is also possible that the underlying solver throws an error and the whole iteration procedure is cancelled. It would be beneficial, if the iteration procedure might continue e.g. with another trial for bisection or with a new adaption from the line search or to at least return the last feasible solution (if there is one).

Hence, an option that allows to turn on/off the error of ther underlying solver would be beneficial.

**Comment by JOlucak** [comment]
Remark:
The error message and the matlab aboard mechanism should be turn off. In the code we should add our "own" check that allows us to control what happens next.

**Comment by tcunis** [comment]
The option you are looking for is *`error_on_fail`* defined in [`FunctionCommon`](https://github.com/iFR-ACSO/casos/blob/9075b8b065128d7a926527a6269d808e52a03f7c/%2Bcasos/%2Bpackage/%2Bfunctions/FunctionCommon.m). We already use it in the quasiconvex solver, viz.

```
% SOS options
sosopt = opts.sossol_options;
sosopt.Kx = struct('lin',Nl,'sos',Ns);
sosopt.Kc = struct('lin',Ml,'sos',Ms);
sosopt.error_on_fail = false;
```
([`QuasiconvBisection/buildproblem`, ll. 42–46](https://github.com/iFR-ACSO/casos/blob/9075b8b065128d7a926527a6269d808e52a03f7c/%2Bcasos/%2Bpackage/%2Bsolvers/%40QuasiconvBisection/buildproblem.m#L46))
