### ISSUE TITLE
Improve computation times of PS operations

### ISSUE THREAD

**Issue by JOlucak** [iFR-ACSO/casos#63]
Some basic math operations, espacially mtimes seem to be very time consuming (see screenshot from a 2D reachability example using sequential SOS). Can we improve runtime of  these functions?
![grafik](https://github.com/iFR-ACSO/casos/assets/61011693/6bed4b2c-cd9d-4ec0-8b38-2ee6e41298ad)

The other screenshot show more in details which lines/subfunctions are responsible:
![grafik](https://github.com/iFR-ACSO/casos/assets/61011693/873cae19-f818-4700-9f40-6852a9edaa30)
![grafik](https://github.com/iFR-ACSO/casos/assets/61011693/faa465da-65bd-49f3-ba35-c249f7754f35)
![grafik](https://github.com/iFR-ACSO/casos/assets/61011693/967126d1-780e-4a48-baa5-03ee570e1a72)

**Comment by JOlucak** [comment]
Additional remar: The sparsity.common.mtimes seems to be kind of the bottleneck (also in uniqueDeg).

**Comment by tcunis** [comment]
The implementation of `PS/mtimes` is legacy code from multipoly, it is possible that it could be improved but right now, I don't how nor do I have capacity to work on it.

As for `casadi.Sparsity/mtimes` and its use in `PS/uniqueDeg`, it's the best we can get in the current implementation. Unless we switch to C++, use `casadi.MX` for the coefficients, or implement polynomial operation trees ourselves, the only *other* option we had is to reduce the number of times `PS/uniqueDeg` is called.

**Comment by tcunis** [comment]
@JOlucak: When used in `pnorm2`, the matrix product always takes the form of a inner vector product (row vector * column vector). The linked branch, [`polynomial-mtimes`](https://github.com/iFR-ACSO/casos/tree/polynomial-mtimes), implements an improved matrix product for this special case. Please check out.

**Comment by tcunis** [comment]
Some improvements have been made by ongoing development but overall, there is not much we can do about the computation time here.
